### ISSUE TITLE
Add more information to Translation Dashboard Status

### ISSUE THREAD

**Issue by sebastiaanspeck** [tldr-pages/tldr-maintenance#133]
Right now we have a summary table to show the total metrics, but if there are issues, you need to look at "every" language to find which languages have the issues. Maybe we can add an extra header to list all affected pages per metric (if there are less than 1000(?, this number needs to be checked to not exceed the maximum number of characters in the body).

An example could be:
```md
## Detailed Breakdown by Metric
<details>

<summary>3 malformed or outdated more info link page(s)<summary>

- [pages.es/common/aws-ce.md](https://github.com/tldr-pages/tldr/edit/main/pages.es/common/aws-ce.md)
- [pages.ko/common/aws-ce.md](https://github.com/tldr-pages/tldr/edit/main/pages.ko/common/aws-ce.md)
- [pages.pl/common/http.md](https://github.com/tldr-pages/tldr/edit/main/pages.pl/common/http.md)
</details>
```

**Comment by sbrl** [comment]
Sounds like a good plan. The limit may be a problem for new tests though.

I wonder if it would be possible to e.g. link to an Actions artefact in the case of a large number of pages that fail a specific test?
