### ISSUE TITLE
How can we make these metrics more visible?

### ISSUE THREAD

**Issue by sebastiaanspeck** [tldr-pages/tldr-maintenance#20]
I noticed that other maintainers didn't know their language was so outdated until I opened specific issues per language. With this issue I would like to think about a way so that maintainers will see earlier that their maintained language is outdated. Signalling early keeps the pile small.

Feel free to drop your idea here

@kbdharun

**Comment by spageektti** [comment]
Maybe this is kinda offtopic but IMO instead of using artifacts, we should put the resultd in a more visible place, like releases or something

**Comment by kbdharun** [comment]
I think designing a frontend site to display the statistics and also visualize the languages would work the best (we can push the current assets to releases, and get them on the site).

**Comment by kbdharun** [comment]
> I checked, but we can only upload a maximum of 100 artifacts per GH Release. We could upload the metrics.zip, but that still requires the user to download it first. Edit: see https://github.com/tldr-pages/tldr-maintenance/pull/21 for a release-setup

I am not sure where you got the statistics from, but GitHub releases don't have a limit on the number of artifacts that can be uploaded/overwritten for a single release rather there is a size restriction of 2 GB for each artifact file.

> I like the idea of keeping things in GitHub. Since we have multiple languages, do we want to create 1 issue or 1 issue per language? To me, 1 issue per language is better.

We can go with an approach like this i.e. open issues per language here on this repo and create an issue with an overall dashboard in the main repo and link to the issue here.

**Comment by kbdharun** [comment]
Great work @sebastiaanspeck, just went through all the dashboards. Btw, does it create a new issue when we add a language to the main repository?

**Comment by kbdharun** [comment]
> Is there anything for now we want to improve or can we close this issue?

We can close this issue, now that we have dashboards for each languages and the concerns has been addressed. Once again, thanks for taking your time to make this integration.
